name: "CI workflow"
on: 
  push

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Step1
     run: echo "Hello my name $HOSTNAME"
   - name: Step2
     run: |
       echo " Hello Team Today is $`date` "
       
       
   
 
